# Creating Numpy Arrays

In [1]:
import numpy as np

There are 6 general ways to create a nympy array:
- Conversion from other Python structures (i.e. lists and tuples)

- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

- Replicating, joining, or mutating existing arrays

- Reading arrays from disk, either from standard or custom formats

- Creating arrays from raw bytes through the use of strings or buffers

- Use of special library functions (e.g., random)

Forr detailed info ref - https://numpy.org/doc/stable/user/basics.creation.html

***Array Creation M-1 : Conversion from other Python structures (i.e. lists and tuples)***

In [2]:
arr1 = np.array([[2, 1, 0], [1, 0, 0], [3, 2, 1]]) #creating from a py list
arr2 = np.array({34, 45, 56, 67}) #creating from a py tuple

In [3]:
arr1

array([[2, 1, 0],
       [1, 0, 0],
       [3, 2, 1]])

In [4]:
arr2

array({56, 34, 67, 45}, dtype=object)

In [7]:
arr1.shape

(3, 3)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.size

9

In [10]:
arr2.shape

()

In [11]:
arr2.dtype

dtype('O')

In [12]:
arr2.size

1

***Array Creation M-1 : Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)***

np.zeros(n) is a numpy function which creates a numpy array containing n no. of elements all as "0"

In [14]:
z1 = np.zeros(10)
z2 = np.zeros((2, 6))

In [15]:
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
z1.shape

(10,)

In [17]:
z1.dtype

dtype('float64')

In [18]:
z1.size

10

In [19]:
z2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
z2.shape

(2, 6)

In [21]:
z2.dtype

dtype('float64')

In [22]:
z2.size

12

np.arange(n) is a numpy function which creates a numpy array containing n-1 elements ranging as 0 to n-1

In [24]:
r1 = np.arange(15)

In [25]:
r1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

np.linspace(n1, n2, n) is a numpy function which creates a numpy array containing n elements starting from n1 to n2 such a that all the elements are equally spaced.

In [26]:
n1 = np.linspace(1, 10, 7)

In [27]:
n1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

np.empty(arg1, ...) is a numpy function which creates a numpy array with the size arg1 with completely empty space. That is, it just assigns the given memory for that array.

In [29]:
e1 = np.empty(10)

In [30]:
e1

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

np.empty_like(arr) is a numpy function which creates an array using another array which is previously created, but this new array will have copied all the elements form the initial array.

In [31]:
e2 = np.empty_like(r1)

In [32]:
e2

array([      0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,    1616,       0,       0, 7602273,
             0])

there are also similar functions like: ones_like(arr)(Return an array of ones with shape and type of input.), zero_like(arr), full_like(arr)(Return a new array with shape of input filled with value), etc

np.identity(arg1) returns a identity matrix of size arg1

In [34]:
i1 = np.identity(10)

In [35]:
i1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

arr.reshape(arg1, arg2, .....) is numpy function which returns a numpy array with the given arg as its dimensions. To give the correct dimensions ensure that the new dimensions product is equal to the old dimensions.

In [38]:
r1.reshape(3, 5) #this doesn't updates the orignal array.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
#to change it, write the reshape function as : 
r1_modified = r1.reshape(3, 5)

In [40]:
r1_modified

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

arr.ravel() is a numpy function which returns the array as 1-D. that is it removes all the rows and keeps all the elements in a single row.

In [41]:
r1_modified.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])