In [1]:
import numpy as np

In [8]:
p1 = [12, 13, 14]
p2 = [1, 2, 3]

In [9]:
p1 + p2

[12, 13, 14, 1, 2, 3]

In [3]:
a1 = np.array([[0, 1, 1], [2, 1, 2], [3, 2, 1]])
a2 = np.array([[1, 3, 2], [1, 1, 4], [3, 2, 5]])

In [4]:
a1 + a2

array([[1, 4, 3],
       [3, 2, 6],
       [6, 4, 6]])

In [5]:
a1 - a2

array([[-1, -2, -1],
       [ 1,  0, -2],
       [ 0,  0, -4]])

In [6]:
a1 * a2

array([[0, 3, 2],
       [2, 1, 8],
       [9, 4, 5]])

In [7]:
a1 / a2

array([[0.        , 0.33333333, 0.5       ],
       [2.        , 1.        , 0.5       ],
       [1.        , 1.        , 0.2       ]])

In [10]:
a1 + p1

array([[12, 14, 15],
       [14, 14, 16],
       [15, 15, 15]])

In [11]:
np.sqrt(a2)

array([[1.        , 1.73205081, 1.41421356],
       [1.        , 1.        , 2.        ],
       [1.73205081, 1.41421356, 2.23606798]])

In [12]:
a1.sum()

13

In [13]:
a1.max()

3

In [14]:
a1.min()

0

In [15]:
np.where(a1>5)

(array([], dtype=int64), array([], dtype=int64))

In [17]:
type(np.where(a1>5))

tuple

In [18]:
np.nonzero(a1)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [19]:
np.count_nonzero(a1)

8