# Numpy Axis

In [1]:
import numpy as np

In [2]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
ar = np.array(x)

In [5]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
ar.ndim

2

In [7]:
ar.size

9

In [8]:
ar.sum(axis = 0)

array([12, 15, 18])

In [9]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [10]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
 ar.flat

In [12]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
ar.argmax()

8

In [14]:
ar.argmin()

0

In [15]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [16]:
ar.argmax(axis = 0)

array([2, 2, 2], dtype=int64)

In [17]:
ar.argmax(axis = 1)

array([2, 2, 2], dtype=int64)

In [18]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)