In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
a = np.array([37, 45, 54, 345, 90])
a8 = np.array([4, 5, 6, 7, 8, 9, ], np.int8) #an array which holds 8-bit numbers
a16 = np.array([679, 35, 5799, 76, 345], np.int16)  #an array which holds 16-bit numbers
#we can create similar arrays containing 32 as well as 64 bit numbers
# the default type is 32-bit 

In [5]:
a

array([ 37,  45,  54, 345,  90])

In [6]:
a8

array([4, 5, 6, 7, 8, 9], dtype=int8)

In [7]:
a16

array([ 679,   35, 5799,   76,  345], dtype=int16)

In [8]:
a[3]

345

In [10]:
a16[4]

345

In [11]:
a.shape #shows the index info of the array

(5,)

In [12]:
a.dtype #shows the type of numbers the array is holding

dtype('int32')